# Your SonarCloud Organization
sonar.organization=bilalbaddi

# Your exact Project Key
sonar.projectKey=Bilalbaddi_Multi_agentic_system

# A display name for your project
sonar.projectName=Multi-AI Agent Project

# Tell SonarCloud to scan everything in the main directory
sonar.sources=.

# Tell SonarCloud to ignore your virtual environment so it doesn't scan installed libraries
sonar.exclusions=venv/**, **/*.jpg, **/*.png